services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlwriter_dev
    build:
      context: .
    ports: 
      - 1434:1433
    environment:
      - MSSQL_SA_PASSWORD=pass!w0rld1
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express