name: gc-pipeline
on: 
  push:
      branches-ignore:
      - master
jobs:
  Build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9

      - name: Build
        run: |
          dotnet restore --locked-mode
          dotnet build -c Release

      - name: Tests
        run: dotnet test -c Release --no-build -v normal --logger "trx;LogFileName=test-results.trx"

      - name: Publish test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: '**/test-results.trx'